### ISSUE TITLE
Bug - Golden Kykinite Materials are not recognized by Piglins as gold.

### ISSUE THREAD

**Issue by Siuolplex** [Siuolthepic/Kykinite#6]
Dev note: Tag for this is kinda non existant.
Roadmap for Fix is 1.1.0

**Comment by kwpugh** [comment]
There are minecraft tags for piglin items

![Screen Shot 2020-11-24 at 7 36 31 PM](https://user-images.githubusercontent.com/8809210/100171612-71887700-2e8c-11eb-90ed-c418a8dcb879.png)
![Screen Shot 2020-11-24 at 7 36 51 PM](https://user-images.githubusercontent.com/8809210/100171626-72210d80-2e8c-11eb-925d-632339534a75.png)

**Comment by Siuolplex** [comment]
Yeah, Im pretty sure this bug was fixed with 1.0.1 as I wanted to slip the fix in with it. 1.0.1 was more an emergency update anyways.

**Comment by Siuolplex** [comment]
Yeah I was dumb this new update should fix stuff. I will reopen if its not fixed.
